/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syswin_temail_vault_jni_CipherJni */

#ifndef _Included_com_syswin_temail_vault_jni_CipherJni
#define _Included_com_syswin_temail_vault_jni_CipherJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syswin_temail_vault_jni_CipherJni
 * Method:    generateKeyPair
 * Signature: ()Lcom/syswin/temail/vault/jni/CipherJni/KeyPair;
 */
JNIEXPORT jobject JNICALL Java_com_syswin_temail_vault_jni_CipherJni_generateKeyPair
  (JNIEnv *, jobject);

/*
 * Class:     com_syswin_temail_vault_jni_CipherJni
 * Method:    encrypt
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_syswin_temail_vault_jni_CipherJni_encrypt
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     com_syswin_temail_vault_jni_CipherJni
 * Method:    decrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_syswin_temail_vault_jni_CipherJni_decrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_syswin_temail_vault_jni_CipherJni
 * Method:    sign
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_syswin_temail_vault_jni_CipherJni_sign
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     com_syswin_temail_vault_jni_CipherJni
 * Method:    verify
 * Signature: ([BLjava/lang/String;[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_syswin_temail_vault_jni_CipherJni_verify
  (JNIEnv *, jobject, jbyteArray, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
